### ISSUE TITLE
[Suggestion]: 希望优化信息弹窗的遮挡问题

### ISSUE THREAD

**Issue by fishyy119** [ximu3/vnite#101]
### 建议内容

![Snipaste_2024-12-14_18-43-26](https://github.com/user-attachments/assets/0c22e67e-9e4a-4dd2-a39c-f25342845b94)
如图，信息弹窗会挡住操作按钮（在非最大化的情况下甚至会完全遮挡），而用户只能等待他自然消失。
或许可以像VSCode那样加个关闭按钮，或者让其省略显示。

**Comment by ximu3** [comment]
下个版本会优化。

**Comment by ximu3** [comment]
已修复。
