### ISSUE TITLE
游戏统计时间出错

### ISSUE THREAD

**Issue by qazwsx3068** [ximu3/vnite#11]
### 软件版本

1.0.6

### 问题描述

游戏在添加后启动过一下，之后今天看发现时间错误，日志未见更新，游戏是神楽黎明记这个系列的

### 问题日志

无新日志

### 问题截图

![IMG_20240901_124056](https://github.com/user-attachments/assets/bb1e3e54-fc63-4f03-8799-2942cb1eca6f)

**Comment by ximu3** [comment]
我这边暂时没有复现这个bug，不过我尝试调整了计时器的相关部分，还请更新版本后测试下。

**Comment by ximu3** [comment]
至于已出现错误记录的游戏，请在游戏设置-高级-数据库-gameDuration项中调整成对应的秒数

**Comment by qazwsx3068** [comment]
ok
