### ISSUE TITLE
[Suggestion]: 希望将自动配置运行目录的功能的触发按钮提供给用户

### ISSUE THREAD

**Issue by fishyy119** [ximu3/vnite#110]
### 建议内容

![Snipaste_2024-12-21_19-48-47](https://github.com/user-attachments/assets/11fd130c-d2c9-412d-a330-4499308cb32e)
如上图，此界面的运行相关配置，一般在用户初次设置完第二个选项卡的路径后，这个页面的内容会自动填充上，极大减少了用户的重复操作量，但是并不能由用户手动触发，希望提供一个按钮，允许用户手动触发此功能。

此功能大概有两个使用场景：
- 用户初次设置文件路径，此时此页面内容为空，能够进行自动填充
  > 但是这个功能会因为不知名原因失效，在我的电脑上已经出现了两次，目前无法稳定复现
- 用户文件路径发生了变化，需要修改文件路径，此时程序没有足够的信息来决定是否要进行自动填充
  > 虽然现在可以通过手动删除运行配置，来间接触发自动填充的功能，但还是太繁琐了，而且也过于模糊

我认为增加一个手动触发的按钮，就能够更好的覆盖这两种使用场景，同时也能在现在的自动填充失效的情况下由用户快速修正

**Comment by ximu3** [comment]
点击右上角的预设配置，点击默认配置，即可手动触发填充。
