### ISSUE TITLE
[Feat]: 关于自动批量刮削

### ISSUE THREAD

**Issue by YamadaKinji** [ximu3/vnite#15]
### 功能描述

在现在的添加游戏的逻辑上，能做成半自动刮削吗？

### 实现思路

可以直接按照某文件夹下的文件夹名进行刮削。考虑到有的游戏不能在中文路径下，比如可以同时支持日文原文或者GID等的命名方式。具体的启动路径可以在首次启动时提示设置，其它的背景图之类的可以默认第一张，用户不喜欢的话再手动选择

**Comment by ximu3** [comment]
会尝试实现，可能会受限于api速率

**Comment by YamadaKinji** [comment]
> 会尝试实现，主要是批量刮削可能会受限于api速率

感谢老板。就个人而言，慢慢刮也会比全部手动导入要好的。

**Comment by ximu3** [comment]
新版本已添加批量刮削
