### ISSUE TITLE
[Bug]: 添加最后一个角色的vhd一直等待

### ISSUE THREAD

**Issue by lingshi123** [ximu3/vnite#17]
### 软件版本

126

### 问题描述

添加最后一个角色的vhd一直等待，试了好几个游戏都是这样

### 问题日志

[app.log](https://github.com/user-attachments/files/16981166/app.log)

### 问题截图

![image](https://github.com/user-attachments/assets/31c6dcfc-9f37-4fe1-8d39-19dcef2d86ba)

**Comment by ximu3** [comment]
我这边暂时没有复现这个问题，你可以尝试换个网络环境。
再贴一下你的data.json文件，看看是不是数据库损坏导致的，文件在C:\Users\ximu\AppData\Roaming\vnite\app\data\下

**Comment by lingshi123** [comment]
还真是网络的问题，解决了谢谢
