### ISSUE TITLE
关于游戏资源

### ISSUE THREAD

**Issue by user-20240827** [ximu3/vnite#18]
有些游戏搜索不到相应的元数据，比如VenusBlood -FRONTIER-系列，希望以后能支持这些数据，或者能让使用者自己添加，编辑游戏以备不时之需

**Comment by ximu3** [comment]
把游戏程序拖拽到侧边栏即可越过刮削器添加

**Comment by user-20240827** [comment]
原来如此，非常感谢您的解答
