### ISSUE TITLE
[Bug]: 相同的游戏被添加后会重复显示

### ISSUE THREAD

**Issue by wjh191** [ximu3/vnite#19]
### 软件版本

1.2.6

### 问题描述

比如我添加两次`抜きゲーみたいな島に住んでる貧乳はどうすりゃいいですか？`这个游戏，游戏列表会有两个这个游戏，修改其中一个的内容，另一个也会被修改，所以它们都指向了同个游戏，只是会重复显示。

### 问题日志

无

**Comment by ximu3** [comment]
下个版本会修复这个bug，感谢反馈

**Comment by ximu3** [comment]
新版本已经修复
