### ISSUE TITLE
关于一些需求或者是建议

### ISSUE THREAD

**Issue by user-20240827** [ximu3/vnite#21]
希望更新开机自动启动和最小化到托盘这两个功能。
希望能解决一下重复启动的问题，希望能像steam那样直接弹出原来的窗口，而不是启动两个窗口。
如能解决，万分感激。

**Comment by ximu3** [comment]
感谢提议，下个大版本会加
重复启动是指vnite打开后，再次打开vnite.exe会启动新的vnite吗

**Comment by user-20240827** [comment]
对的，因为我是用的win平板，有时点快了就会启动复数个窗口

**Comment by ximu3** [comment]
重复启动的问题新版本已修复

**Comment by ximu3** [comment]
新版本已添加开机自动启动和最小化到托盘这两个功能
