### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by nymph91** [ximu3/vnite#22]
无法下载，需要授权是什么问题，帮帮我谢谢

**Comment by ximu3** [comment]
额，描述的具体点，啥叫无法下载。

**Comment by ximu3** [comment]
给个图和log

**Comment by nymph91** [comment]
![Uploading fba01352ae887ed9dfaaa1affda8c32f.jpg…]()

**Comment by nymph91** [comment]
![Uploading fba01352ae887ed9dfaaa1affda8c32f.jpg…]()

**Comment by nymph91** [comment]
![fba01352ae887ed9dfaaa1affda8c32f](https://github.com/user-attachments/assets/bb9fce84-a49b-485b-8125-f2ce45a10f2b)

**Comment by ximu3** [comment]
这个问题和vnite无关，你用的什么浏览器。

**Comment by nymph91** [comment]
edge

**Comment by nymph91** [comment]
有浏览器限制吗

**Comment by ximu3** [comment]
没限制，但edge可能会阻止一些东西的下载，调设置可以解决（具体怎么调请自行搜索）
或者你换个浏览器下，用Chrome什么的都行

**Comment by nymph91** [comment]
thank u
