### ISSUE TITLE
[Bug]: 启动无法显示已导入GAL

### ISSUE THREAD

**Issue by syjhwsc** [ximu3/vnite#27]
### 软件版本

1.2.7

### 问题描述

每次关闭后重新打开都会无法加载出之前导入的GAL，需要再导入一个新的GAL才能正常加载看到已经导入的GAL

### 问题日志

没有报错问题日志

### 问题截图

![屏幕截图 2024-09-15 182214](https://github.com/user-attachments/assets/8630d88b-4dc8-4d88-a7a4-35af900e513a)
![屏幕截图 2024-09-15 182448](https://github.com/user-attachments/assets/2446b919-70dd-43a7-8c5b-a555eaf05a7a)
![屏幕截图 2024-09-15 182508](https://github.com/user-attachments/assets/00f8babc-8802-4a5e-a563-fa6d5c5b1f56)

**Comment by Sperte-s** [comment]
是新版本特有的问题吗

**Comment by ximu3** [comment]
是新版本特有的问题吗

**Comment by ximu3** [comment]
之前的版本是什么，有这个问题吗

**Comment by syjhwsc** [comment]
1.2.5不存在这个问题，1.2.6不知道没用过

**Comment by syjhwsc** [comment]
刚才试了下1.2.6好像也有这个问题，而且设置里看不见版本号

**Comment by syjhwsc** [comment]
![屏幕截图 2024-09-15 184446](https://github.com/user-attachments/assets/814d8fbd-1748-4a02-bc5c-522c9aeee2fc)

**Comment by ximu3** [comment]
开云同步了吗

**Comment by syjhwsc** [comment]
没开云同步，账号也没登

**Comment by ximu3** [comment]
我本地没有复现这个问题，但可能是因为应用启动时多个进程同时读取一个文件造成的，我调整了相关代码，还麻烦更新测试下。

**Comment by syjhwsc** [comment]
没问题了现在，感谢
