### ISSUE TITLE
[Feat]: 增加刮削途径或支持自定义导入

### ISSUE THREAD

**Issue by syjhwsc** [ximu3/vnite#28]
### 功能描述

可以增加从BANGUMI或者VNDB刮削的功能吗，或者类似playnite的自己导入游戏支持自定义描述设置什么的功能，因为今天碰到了几个GAL无法从月幕上找到数据的情况，然后因为也无法手动导入游戏自己进行编辑只好放弃了这几个GAL的导入，如果可以的话万分感谢

**Comment by ximu3** [comment]
可以手动导入的，把游戏程序拖到左侧游戏列表就可以了

**Comment by syjhwsc** [comment]
感谢，我去试试
