### ISSUE TITLE
[Bug]: 打开媒体文件夹报错

### ISSUE THREAD

**Issue by rxia24** [ximu3/vnite#3]
### 软件版本

1.0.3

### 问题描述

游戏详情页 =》 齿轮按钮 =》 媒体标签页 =》 打开媒体文件夹
会报错：windows找不到文件，像是路径有误。

### 问题日志

没找到logs文件夹。

### 问题截图

![image](https://github.com/user-attachments/assets/8a38b84e-de1a-4ce3-b27f-b2d4c5ed6360)

**Comment by ximu3** [comment]
感谢反馈，已修复。

**Comment by rxia24** [comment]
已修复
