### ISSUE TITLE
[Suggestion]: 游戏本地路径与存档路径的云同步

### ISSUE THREAD

**Issue by MadokaMoonlight** [ximu3/vnite#35]
### 建议内容

由于各个终端的游戏本地路径与存档路径不一定一致，建议云同步时忽略游戏本地路径与存档路径

**Comment by ximu3** [comment]
由于同步时是同步整个数据库的，目前还无法做到忽略某个配置项，我会尝试解决这个问题，感谢提议。

**Comment by MadokaMoonlight** [comment]
请问现在有设置可以关闭对游戏路径和存档路径的同步吗

**Comment by ximu3** [comment]
> 请问现在有设置可以关闭对游戏路径和存档路径的同步吗

不好意思，最近没什么时间，国庆假期会把这个功能写出来。

**Comment by ximu3** [comment]
新版本已经修复了这个问题
