### ISSUE TITLE
[Suggestion]: 建议修改下最近游戏和最近游玩模块的排序规则

### ISSUE THREAD

**Issue by yao074** [ximu3/vnite#36]
### 建议内容

希望最近游戏能够按照游玩次序正确的排列。

还有主页的所有游戏 排序模块，选定一种后，切换到其他界面切回来就重置为按照名称排序的正序排列。
希望可以保留筛选好的状态排序。

如果更进一步优化可以参考steam的最近运行日期的排列方式，按照 年-月份-倒序的排列方法，更加直观。

**Comment by ximu3** [comment]
感谢提议，下个大版本会更新这些内容。目前的最后游玩日期只精确到了日，所以同一天打开多个游戏会出现排序错误。

**Comment by ximu3** [comment]
最新版本已实现这些功能
