### ISSUE TITLE
[Bug]: 游戏高级设置中的游玩状态显示错误

### ISSUE THREAD

**Issue by MadokaMoonlight** [ximu3/vnite#38]
### 软件版本

1.3.2

### 问题描述

1.更改主界面的游戏状态后，数据库中的playStatus不会变更
2.变更playStatus，也不会影响设置中的游玩状态

### 问题日志

无日志

### 问题截图

![Snipaste_2024-09-21_11-29-29](https://github.com/user-attachments/assets/44549b37-a469-44b7-a018-99fc04765733)
![Snipaste_2024-09-21_11-30-17](https://github.com/user-attachments/assets/daccd314-672d-44af-8fb6-ad4d89170a67)

**Comment by ximu3** [comment]
感谢反馈，下个小版本就会修复这个问题

**Comment by ximu3** [comment]
最新版本已修复
