### ISSUE TITLE
希望可以直接添加修改游玩时间

### ISSUE THREAD

**Issue by Theo-lzwk** [ximu3/vnite#39]
想添加一些原来玩过的数据到Vnite，不过现在没有这个功能

**Comment by ximu3** [comment]
目前可以在游戏-高级-数据库中修改，改gameDuration项，以后会添加比较直观的修改方法。

**Comment by ximu3** [comment]
最新版本已支持较直观的修改方法（游戏-设置-高级页）

**Comment by Theo-lzwk** [comment]
感谢
