### ISSUE TITLE
导入游戏资料数据失败

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#40]
使用GID导入数据会卡在这个界面，但通过名字下载数据没有问题
![PixPin_2024-09-22_20-49-36](https://github.com/user-attachments/assets/abcd5fcb-3a4e-4e98-b249-e2e7bc5ef085)

**Comment by ximu3** [comment]
贴日志（软件根目录logs文件夹中）

**Comment by z2023711** [comment]
[Uploading app.log…]()

**Comment by ximu3** [comment]
额，你没传上来
![image](https://github.com/user-attachments/assets/3de823cb-8252-40f6-aff6-586bb16e84e5)

**Comment by z2023711** [comment]
[Uploading app.log…]()

**Comment by z2023711** [comment]
[app.log](https://github.com/user-attachments/files/17096238/app.log)

**Comment by z2023711** [comment]
🤦‍♂️

**Comment by ximu3** [comment]
使用gid导入数据是从哪一步开始出现问题的，是一开始还是下载完所有数据后。
我这边没有复现这个问题，能否提供下出现问题的gid呢

**Comment by z2023711** [comment]
ga48321


只填写这个GID，不写名字就会出现卡顿界面


而填写名字不写这GID，无论名字是否正确都有界面，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月23日(周一) 晚上6:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] 导入游戏资料数据失败 (Issue #40)




 
使用gid导入数据是从哪一步开始出现问题的，是一开始还是下载完所有数据后。
 我这边没有复现这个问题，能否提供下出现问题的gid呢

**Comment by ximu3** [comment]
是点击识别后出现问题的吗

**Comment by z2023711** [comment]
是的，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月23日(周一) 晚上6:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] 导入游戏资料数据失败 (Issue #40)




 
是点击识别后出现问题的吗

**Comment by ximu3** [comment]
怪，我本地复现不了这个bug。

**Comment by z2023711** [comment]
一会儿我试试，如果能复现，我就给你录个视频



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月23日(周一) 晚上7:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] 导入游戏资料数据失败 (Issue #40)




 
怪，我本地复现不了这个bug。

**Comment by ximu3** [comment]
ok，感谢

**Comment by z2023711** [comment]
> ok，感谢

![Uploading PixPin_2024-09-23_19-15-44.gif…]()

**Comment by z2023711** [comment]
![PixPin_2024-09-23_19-19-12](https://github.com/user-attachments/assets/95fd3125-c1e3-480b-a740-7abd330edb99)

**Comment by ximu3** [comment]
感谢录屏，最新版本已经修复了这个问题。
