### ISSUE TITLE
[Bug]: 在已添加一个或多个游戏后，直接添加功能使用失败

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#41]
### 软件版本

1.4

### 问题描述

在已添加一个或多个游戏后，直接添加功能使用失败

### 问题日志

[app.log](https://github.com/user-attachments/files/17114783/app.log)

### 问题截图

https://github.com/user-attachments/assets/3976489a-6260-4862-9e39-f705fc1f3e70

**Comment by ximu3** [comment]
是特定游戏失败还是全都失败

**Comment by z2023711** [comment]
之前失败时是全都不行，但是我刚才重新打开软件，发现列表上出现了游戏，然后，我又尝试加载其他游戏都成功了，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月24日(周二) 晚上9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] [Bug]: 在已添加一个或多个游戏后，直接添加功能使用失败 (Issue #41)




 
是特定游戏失败还是全都失败

**Comment by ximu3** [comment]
应该是前端数据更新的问题，我会优化下，感谢反馈

**Comment by z2023711** [comment]
那个，可能又出现bug了，有一个游戏，月慕没有但vndb有，也就是说有封面，我想导入封面然后再自己完成数据库，不过最后它显示游戏数据导入失败，这以后我的所有游戏就都没了，
有数目，但是没游戏，重启软件也没用，

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月24日(周二) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] [Bug]: 在已添加一个或多个游戏后，直接添加功能使用失败 (Issue #41)




 
应该是前端数据更新的问题，我会优化下，感谢反馈

**Comment by z2023711** [comment]
![PixPin_2024-09-24_21-45-44](https://github.com/user-attachments/assets/d8448335-b6f8-4bfe-b4ef-673cbf61991d)
[app.log](https://github.com/user-attachments/files/17115628/app.log)

**Comment by ximu3** [comment]
是直接添加后又在该游戏界面选择下载资料数据后出现问题的吗

**Comment by ximu3** [comment]
不好意思，我的疏忽，这个刮削器是以月幕为主导的，月幕没有数据的情况下刮削会出错，导致数据库损坏，我马上发版修复。

**Comment by z2023711** [comment]
> 不好意思，我的疏忽，这个刮削器是以月幕为主导的，月幕没有数据的情况下刮削会出错，导致数据库损坏，我马上发版修复。

好的，麻烦了。

**Comment by ximu3** [comment]
最新版本已修复，但数据应该是无法找回了，请删除c盘的vnite数据库文件夹后更新。（路径在C:\Users\用户名\AppData\Roaming\vnite\ 下的app文件夹）

**Comment by z2023711** [comment]
> 最新版本已修复，但数据应该是无法找回了，请删除c盘的vnite数据库文件夹后更新。（路径在C:\Users\用户名\AppData\Roaming\vnite\ 下的app文件夹）



> AppData\Roaming\vnite

好的。可以了

**Comment by z2023711** [comment]
> 最新版本已修复，但数据应该是无法找回了，请删除c盘的vnite数据库文件夹后更新。（路径在C:\Users\用户名\AppData\Roaming\vnite\ 下的app文件夹）
好像又来bug了😓

**Comment by ximu3** [comment]
啊这，什么bug

**Comment by z2023711** [comment]
> 啊这，什么bug
游戏无法导入
[app.log](https://github.com/user-attachments/files/17116893/app.log)

**Comment by ximu3** [comment]
有删除app文件夹后再更新吗，是要整个删除app文件夹而不是app文件夹下的东西

**Comment by z2023711** [comment]
> 有删除app文件夹后再更新吗，是要整个删除app文件夹而不是app文件夹下的东西

依旧是不行，我试试重装吧

**Comment by z2023711** [comment]
> 有删除app文件夹后再更新吗，是要整个删除app文件夹而不是app文件夹下的东西
将文件删除后，重装了软件可以了

**Comment by ximu3** [comment]
ok，感谢你的耐心反馈:D
