### ISSUE TITLE
[Feat]: 如果要刮削 vndb 的数据应该能让用户指定 vndb 的 vid

### ISSUE THREAD

**Issue by windowBR** [ximu3/vnite#42]
### 功能描述

碰到了刮削错误的情况，苍之彼方的四重奏刮削时月幕 gal 的数据是正常的，但是 vndb 的却刮削错误了，导致封面和背景都是对不上的情况，然而我似乎并没有找到指定 vid 刮削的功能

**Comment by windowBR** [comment]
当然更好的方案是如果有Steam端的游戏直接从Steam获取数据，而月幕Gal对于有Steam端的游戏都会给出链接，应该相当容易自动搜索到对应游戏吧

**Comment by ximu3** [comment]
现在刮削器还不支持使用vndb刮削（目前vndb只是通过游戏日文名刮削了封面和背景图，可能会不准确），不过有支持vndb刮削器的计划，还请等待更新。
下个大版本会支持指定vid刮削背景图和封面的功能。

**Comment by windowBR** [comment]
嗯，我的意思就是目前的自动刮削封面和背景不准确，所以希望能指定vid刮削封面背景

**Comment by ximu3** [comment]
下个大版本会有。

**Comment by ximu3** [comment]
最新版本已实现这个功能

**Comment by windowBR** [comment]
功能入口存在问题
我找了大半天后也没找到指定vid刮削的地方，最后才发现只有新增的游戏可以指定gid，而已添加的游戏还无法指定vid重新刮削，应当在已添加游戏的刮削菜单内也添加同样的选项

**Comment by ximu3** [comment]
我的疏忽，这就修复。

**Comment by ximu3** [comment]
已修复

**Comment by rxia24** [comment]
更新到已添加的游戏还无法指定vid重新刮削,
已经更新到 1.5.5
游戏名: "聖ヤリマン学園パコパコ日記2021"
Vid: "v32157"
还是会识别到错误的游戏。

**Comment by ximu3** [comment]
> 已经更新到 1.5.5， 但是已添加的游戏还无法指定vid重新刮削, 游戏名: "聖ヤリマン学園パコパコ日記2021" Vid: "v32157" 还是会识别到错误的游戏。

vid只能辅助刮削背景图和封面，如果要准确刮削其它元数据的话请指定gid。我这边指定vid识别出来的背景图和封面是正确的。
