### ISSUE TITLE
[Bug]：webdav同步出现问题

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#43]
### 软件版本

1.4.2

### 问题描述

配置好（坚果云）webdav后，界面仍显示未完成，点击上传，显示失败
![PixPin_2024-09-27_17-39-06](https://github.com/user-attachments/assets/6ec7ea28-21d1-40a4-bf2f-902ac389fe58)
但你点击下载，就会显示如下：
![PixPin_2024-09-27_17-39-48](https://github.com/user-attachments/assets/30536430-760b-4c42-997f-f90421744c00)
然后再点击上传，显示如下：
![PixPin_2024-09-27_17-39-58](https://github.com/user-attachments/assets/23d6269f-ac9f-40a3-accc-1b16fc756046)
但实际上，你的云端一点文件都没有
![PixPin_2024-09-27_17-44-25](https://github.com/user-attachments/assets/02822cc7-bd41-4c31-828c-5c750c2d266c)

### 问题日志

[app.log](https://github.com/user-attachments/files/17162344/app.log)

**Comment by ximu3** [comment]
webdav没写完，现在只能用github同步

**Comment by z2023711** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月27日(周五) 晚上6:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] [Bug]：webdav同步出现问题 (Issue #43)




 
webdav没写完，现在只能用github同步
