### ISSUE TITLE
[Feat]: 根据游玩状态动态分类

### ISSUE THREAD

**Issue by hengxin001** [ximu3/vnite#46]
### 功能描述

游戏主界面有游玩状态的选项，能不能根据游玩状态自动分组，当切换游戏的游玩状态时将游戏自动移动到对应的分类？

**Comment by ximu3** [comment]
感谢提议，会在下个大版本考虑添加这个功能。

**Comment by ximu3** [comment]
v2已经更新了这个功能，还请更新版本。

**Comment by hengxin001** [comment]
> v2已经更新了这个功能，还请更新版本。

已经更新，但我没有找到相关功能，我的收藏仍然只有我自己创建的那几个分类。目前切换游玩状态没有看见有什么变化。

**Comment by ximu3** [comment]
草，我的，目前动态分类只支持发行商、分类和标签，还没把游玩状态写进去。

**Comment by ximu3** [comment]
新版本已添加该功能
![image](https://github.com/user-attachments/assets/f176763d-344b-4e74-9d45-012e4d295359)
