### ISSUE TITLE
[Bug]: 最小化到托盘后软件自动退出

### ISSUE THREAD

**Issue by hengxin001** [ximu3/vnite#47]
### 软件版本

1.5.2

### 问题描述

电脑系统Win11，关闭主面板的动作选择的是最小化到托盘。
关闭主界面后软件最小化到托盘，一段时间后软件会自动关闭。
只要关闭了软件主界面，那么就算再从托盘图标打开软件也依然会退出。

### 问题日志

[app.log](https://github.com/user-attachments/files/17242437/app.log)

**Comment by ximu3** [comment]
感谢反馈，会尝试修复这个问题。

**Comment by ximu3** [comment]
已修复
