### ISSUE TITLE
[Suggestion]: 部分游戏存档特殊情况

### ISSUE THREAD

**Issue by Liu201909** [ximu3/vnite#52]
### 建议内容

**SMEE社的游戏存档很特殊，是单独一个文件，即BGI.gdb，**比如HaremKingdom、ピュア×コネクト －PURE×CONNECT等，而且这个文件是和游戏exe同个文件夹，这样如果要同步，可能不得不同步上一个父文件夹，但是要同步的量肯定上GB了，比如HaremKingdom就有3GB多，这给同步带来不太方便，所以大佬能不能加一个只同步单个文件的模式？十分感谢。

**Comment by ximu3** [comment]
下个大版本会更新这个功能，感谢提议。
