### ISSUE TITLE
[Suggestion]: v2功能需求

### ISSUE THREAD

**Issue by ximu3** [ximu3/vnite#60]
由于 vnite 初版设计的不成熟，v2 将使用 ts 彻底重写。
在这个 issue 写下你对 v2 的期待，想要什么新功能、新改进都可以在该 issue 下提出。

**Comment by Liu201909** [comment]
1. 希望多加点类别个数。
2. 希望多加点bangumi，DLsite，Fanza，steam刮削器，然而DLSite和Fanza好像之前作者没有继续开发，有点问题，之前是能用，但是后来DLSite改RJ号就不能用，网址：https://github.com/erri120/Playnite.Extensions，是playnite上的，不知道这个对大佬有没有用。
3. 希望添加几个筛选器，能够根据年份，发行商，开发商，类别等进行筛选，就是每个框对应一个筛选条件，然后可以对一个框或多个框输入条件，进行筛选。
4. 如果2.0出来后，希望可以加点对1.0版本数据的导入机制。

**Comment by endyan** [comment]
1.我觉得当前之急应该优先完善对其它gal数据库的支持，建议优先使用圈内公认gal最全的VNDB(vndb.org)，还有bangumi（https://bangumi.tv/game）也可以备选，月幕gal的数据还是相对偏少
2.如果有存在数据刮削错误的gal可通过编辑gal正确名字+可选择数据库源+对应数据库ID之后，可以直接在编辑界面从当前编辑的数据源更新资料数据，就不需要返回到游戏主界面右边三个点那里再重新“下载资料数据”了
3.希望能通过正则表达式匹配游戏所在文件夹名字，作为游戏名检索资料数据。例如单独添加一个gal，可以默认一个正则匹配exe程序所在文件名作为游戏名去检索数据源信息，假如gal安装默认全英文路径，又或者有非全英文路径运行出错的gal就手动修改
4.希望增加筛选分类功能，例如按年份，开发商，开发人员（编剧，声优之类）等，还有分类编辑功能
5.希望主页增加鼠标右键的交互小菜单功能，例如编辑，LE启动，删除等
6.还有跳转到游戏所在文件夹的功能,也就是文件管理器打开文件夹
7.希望增加游玩状态功能设定，状态有按在玩，搁置，玩过，抛弃等，还有增加个人评分

**Comment by ximu3** [comment]
#72

**Comment by fishshi** [comment]
https://github.com/ximu3/vnite/issues/68#issuecomment-2445885123
不确定是否真的需要
