### ISSUE TITLE
[Suggestion]: "最近游戏"栏横条滚动更为美观

### ISSUE THREAD

**Issue by noselenar** [ximu3/vnite#67]
### 建议内容

![image](https://github.com/user-attachments/assets/ac0a6c6e-63a0-4b6a-85f0-a72ab062984e)
当最近游戏数量超过一定数目时，会自动向下排列，添加类似steam的横向滚动会更为美观。

**Comment by ximu3** [comment]
2.0会添加这个功能，感谢提议
