### ISSUE TITLE
[Bug]: 主页“按添加日期排序”的升序与降序切换失效

### ISSUE THREAD

**Issue by noselenar** [ximu3/vnite#68]
### 软件版本

1.5.10

### 问题描述

主页“按添加日期排序”的升序与降序切换失效，且顺序错误（降序排列时最新添加的游戏并没有排在最前），且重启无效。

### 问题日志

无

### 问题截图

![image](https://github.com/user-attachments/assets/5a172477-5153-406e-9669-a3c1b06d8d56)
![image](https://github.com/user-attachments/assets/e53e0a1f-7417-494f-906e-eeb8b385577c)

**Comment by fishshi** [comment]
这是因为按 `添加日期排序` 只能精确到天，当多个游戏都是同一天添加的就会出现顺序不确定的问题。此外，该顺序其实取决于你上一个排序方式的相对顺序。因此，个人感觉不算bug。

**Comment by fishshi** [comment]
这是大概是因为这些游戏都是同一天添加的，`按添加日期排序` 只能精确到天。事实上，该排序下同一天内添加游戏的顺序与上一排序的相对顺序相同。

**Comment by fishshi** [comment]
如果需要 `按添加时间排序`，或许可以在v2中添加。迁移数据库时可以通过文件的创建时间一定程度上获取先前缺失的时间部分。
但是我不确定是否真的需要此精度的排序。

**Comment by ximu3** [comment]
v2将使用ISO 8601 标准储存所有时间相关的数据，精确到毫秒，会解决这个问题。

**Comment by noselenar** [comment]
感谢关注，辛苦了
