### ISSUE TITLE
[Feat]: 能否加一个本地攻略打开的功能

### ISSUE THREAD

**Issue by wycstc353** [ximu3/vnite#72]
### 功能描述

能否加一个本地攻略打开的功能，我文件夹内有份这个游戏的攻略，可能是txt，可能是word，也可能是图片，希望加一个打开攻略的功能，直接从大佬的exe打开攻略，而不是要打开游戏文件夹，自己重新打开攻略

**Comment by ximu3** [comment]
2.0会考虑添加，感谢提议。
