### ISSUE TITLE
[Bug]: 在发现刮削有误后重新输入gid刮削数据后 刮削进程卡死

### ISSUE THREAD

**Issue by okami2012** [ximu3/vnite#73]
### 软件版本

1.5.10

### 问题描述

搜索游戏的时候搜索到游戏名称了 但是点完了刮削有可能会卡死 卡死后不能取消

### 问题日志

无

### 问题截图

![7585019519f148ce33b12d0a98c49391](https://github.com/user-attachments/assets/cbe6011e-4ce9-4755-8a24-b44eec84ee41)
发现刮削错误
![742ee3bac280dc559bac3cd5b5f389d4_720](https://github.com/user-attachments/assets/308ce09d-7fbd-47c5-a680-e05e9ee85f28)
返回重新刮削
![5414e2c506277ee1a5bd3114352bb625](https://github.com/user-attachments/assets/ee230d88-0f7e-44fc-9f99-24f591404e22)
![7f17917b4f940f4893a4083591d00977](https://github.com/user-attachments/assets/fc4e6108-8b82-4694-a2ae-a8e827ce27d2)
提示 请等待操作完成

**Comment by fishshi** [comment]
再次点击识别之前在GID前加上'ga'可以避免此问题，但是确实是bug。

**Comment by ximu3** [comment]
已修复 @fishshi in https://github.com/ximu3/vnite/pull/74
