### ISSUE TITLE
[Bug]: 资料库识别

### ISSUE THREAD

**Issue by fisher66616** [ximu3/vnite#77]
### 软件版本

v1.5.12

### 问题描述

下载资料库数据不能输vid识别，开加速器也不行

### 问题日志

![Uploading PixPin_2024-11-03_20-22-12.png…]()

### 问题截图

![PixPin_2024-11-03_20-22-12](https://github.com/user-attachments/assets/b487ac5f-476c-467f-9c5b-c6597047a6fa)

**Comment by fishshi** [comment]
v1版本添加游戏时使用的数据源是以 `月幕gal` 为主，`vndb` 为辅。
因此目前暂不支持单vid搜刮，即使填写vid也需要同时输入游戏名或gid。
*建议首先只使用游戏名或gid搜刮，当发现待选背景图数据有误时再增加vid辅助搜刮。*
