### ISSUE TITLE
[Bug]: 资料库识别不到

### ISSUE THREAD

**Issue by okami2012** [ximu3/vnite#79]
### 软件版本

1.5.12

### 问题描述

![image](https://github.com/user-attachments/assets/2e4ebca4-8ce5-4e01-a95a-8fcd2d6968eb)
正常月幕是可以搜索到游戏的

### 问题日志

-

### 问题截图

-

**Comment by fishshi** [comment]
您好！填写GID时请使用 `ga` + 数字，如 `ga37792`。谢谢！

**Comment by fishshi** [comment]
https://github.com/user-attachments/assets/cfac6d53-8d4d-40a1-b563-9d0384e01018
我这里测试好像可以...
（教室校园网不好，加载有点慢，但是确实可以找到。）

**Comment by okami2012** [comment]
> https://github.com/user-attachments/assets/cfac6d53-8d4d-40a1-b563-9d0384e01018 我这里测试好像可以... （教室校园网不好，加载有点慢，但是确实可以找到。）

那看来是我网络的问题 我再试试吧
