### ISSUE TITLE
[Bug]: 添加黄昏之药时报错

### ISSUE THREAD

**Issue by prince-dulb** [ximu3/vnite#8]
### 软件版本

1.0.6

### 问题描述

添加《黄昏的禁忌之药》时出现以下报错：
[error] 获取游戏数据时出错：TypeError: Cannot read properties of undefined (reading 'game')
遂重试，但不选择路径，报错依旧

### 问题日志

[app.log](https://github.com/user-attachments/files/16762871/app.log)

### 问题截图

![屏幕截图(85)](https://github.com/user-attachments/assets/65a56a6c-3105-4702-8c56-092a0c8f4de8)

**Comment by prince-dulb** [comment]
尝试添加别的游戏，报错依旧

**Comment by prince-dulb** [comment]
我已尽我可能尝试不同的网络环境和梯子，没有解决。看来在我的位置就是用不了这个软件了

**Comment by zangxycoding** [comment]
遇到了相同问题，更换几个梯子都没用
