### ISSUE TITLE
[Suggestion]: 建议旧版老哥们暂时先别更新到2.0

### ISSUE THREAD

**Issue by yao074** [ximu3/vnite#80]
### 建议内容

一更新到2.0，数据全部不显示。像是清空一样，估计还没做好数据对接。导入1.5保存的数据也无法导入（提示导入成功但是没用）。

顺便说一下2.0的一个bug，设置最小化后，哪怕对着图标右键退出，好像也没反应。必须设置会右上角是关闭功能才能关闭。

更新到2.0的也不用慌，直接下载1.5的重新安装覆盖，数据还是在的（差点心肺停止，上百个游戏再重新刮削就要命了）。

如果可以更新了，求踢我一脚。

**Comment by z2023711** [comment]
我看到这条消息的时候已经晚了，数据没了😂

**Comment by ximu3** [comment]
最小化到托盘后无法退出的bug已经修复，v1数据迁移功能在计划中。

**Comment by ximu3** [comment]
已经更新了导入v1数据库的功能，请在v1-设置-数据库-导出数据库后在v2-设置-数据库-导入v1版本数据库中选择刚刚导出的zip文件即可。
