### ISSUE TITLE
[Bug]: 2.0.0-alpha.0 的二个“矛盾”吧

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#81]
### 软件版本

2.0.0-alpha.0

### 问题描述
其一：游戏状态可能有点问题，无论前面的状态是什么，记录下的状态始终是”未游玩“是需要什么设置吗？

![2024-11-27 09 45 00](https://github.com/user-attachments/assets/4a7ff9eb-21e4-4ce1-b798-3d5484427d79)
![2024-11-27 09 45 12](https://github.com/user-attachments/assets/96c77790-0cec-463f-97fe-9c0305486c1c)

其二：通过“不使用刮削器”的方式导入游戏，然后，再下载游戏数据，最后主界面点击开始游戏时，它还会让你再选择一次“游戏路径”可是这个我在导入时，不就已经选择过了吗？

### 问题日志

[app.log](https://github.com/user-attachments/files/17927254/app.log)

**Comment by ximu3** [comment]
已修复
