### ISSUE TITLE
[Bug]: 界面的这种情况算是bug吗？

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#82]
### 软件版本

2.0.0-alpha.2

### 问题描述

全屏没有问题，但是当你点击
![2024-11-29 08 52 52](https://github.com/user-attachments/assets/4541f510-3e47-4970-9570-add373877f2f)
你就会发现，界面比全屏还要大。
![2024-11-29 08 52 24](https://github.com/user-attachments/assets/ef0e92f3-3398-4a79-9630-7fe007f76a51)
左边的侧边栏和右上角的按钮是无法同时存在的，整体不协调，且这种状态下使用鼠标调整界面只能往大了调，

### 问题日志

[app.log](https://github.com/user-attachments/files/17953216/app.log)

**Comment by ximu3** [comment]
是指在最大化时软件边缘显示不全吗。

**Comment by ximu3** [comment]
我这边暂未复现这个问题，看看有没有类似的反馈吧。
