### ISSUE TITLE
[Bug]: 导入一个游戏时，就弹出这个，只要玩游戏就弹出，重启也没用

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#88]
### 软件版本

2.0.0-beta.2

### 问题描述

![2024-12-08 13 35 29](https://github.com/user-attachments/assets/c35db482-30e2-4236-91fd-d58cb516f322)

### 问题日志

[app.log](https://github.com/user-attachments/files/18050897/app.log)

**Comment by z2023711** [comment]
会不会是因为主文件名称和软件文件名称不能一样？

**Comment by ximu3** [comment]
是只有这个游戏报错，还是所有游戏都报错

**Comment by z2023711** [comment]
所有。而且。我发现打开游戏时没问题。但是你关闭游戏后。他就弹出来了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月8日(周日) 中午1:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] [Bug]: 导入一个游戏时，就弹出这个，只要玩游戏就弹出，重启也没用 (Issue #88)




 
是只有这个游戏报错，还是所有游戏都报错

**Comment by ximu3** [comment]
我本地没有复现这个bug，但我调整了相关代码，还请更新版本测试下。

**Comment by z2023711** [comment]
目前没有问题了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月8日(周日) 晚上7:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] [Bug]: 导入一个游戏时，就弹出这个，只要玩游戏就弹出，重启也没用 (Issue #88)




 
我本地没有复现这个bug，但我调整了相关代码，还请更新版本测试下。
