### ISSUE TITLE
[Suggestion]: 是否可以“文件夹”或者“标签“的形式管理游戏呢？

### ISSUE THREAD

**Issue by z2023711** [ximu3/vnite#89]
### 建议内容

软件本身的分类是按照游戏导入的数据进行的，但是，这些数据并不都是”正确的“或者说完整的，因为他们来自不同的平台，每个游戏在不同的平台的定义本就不同，平台对游戏的定义也不同。很混乱。
![2024-12-08 13 53 20](https://github.com/user-attachments/assets/37ca18fd-19bc-4c34-bb64-8de97971ac92)
![2024-12-08 13 54 25](https://github.com/user-attachments/assets/21bcbc9c-e75f-4c55-b848-3815720d6ff3)
如上图：几个游戏进行分类，同一个游戏居然有两个厂商？即便是两个公司是从属的关系，如果你不进行查询，你就不知道，到底是哪个会社做的。而且，冒险类只有这一个？太不合常理了，我建议增加”自定义的分类“功能，比如文件夹和标签，

**Comment by ximu3** [comment]
有这个功能的，收藏就是完全由用户自定义的，右键游戏，添加收藏。

**Comment by z2023711** [comment]
好的。我去看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月8日(周日) 下午2:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ximu3/vnite] [Suggestion]: 是否可以“文件夹”或者“标签“的形式管理游戏呢？ (Issue #89)




 
有这个功能的，收藏就是完全由用户自定义的，右键游戏，添加收藏。
