### ISSUE TITLE
[Suggestion]: GUI好丑

### ISSUE THREAD

**Issue by lou-xia** [ximu3/vnite#91]
### 建议内容

点进具体游戏内容以后的界面好丑啊，主要是简介字很多很密，看着就难受。
![image](https://github.com/user-attachments/assets/5872f465-a663-4bd1-a81d-2d55b52e4458)
简介这个地方字太多了！！！

**Comment by ximu3** [comment]
可以尝试在简介里加换行，应该会好一些。简介这部分好不好看主要取决于内容，看你能不能刮到排版良好的数据了。

**Comment by ximu3** [comment]
我会尝试优化下简介的字距和行距。
