### ISSUE TITLE
需要查重

### ISSUE THREAD

**Issue by Linyoux** [ximu3/vnite#92]
### 软件版本

2.0

### 问题描述

当我在剥削器添加游戏的时候，连续点击多次时，会产生多个项目。

### 问题日志

无

### 问题截图

![Image_1733845255111](https://github.com/user-attachments/assets/4186a4b2-4b77-4ed3-9fda-29b8f4aebf2f)

**Comment by Linyoux** [comment]
和1.5.12版本体验的差异主要有：
1.剥削不到中文介绍。（大概）
2.批量剥削有问题。
3.2.0版本未能继承1.5.12数据。

**Comment by ximu3** [comment]
中文介绍会在后续版本中更新（现在还没添加月幕作为数据源）
批量刮削具体是什么问题呢？
数据是可以继承的，具体操作可参考文档 https://vnite.ximu.dev/guide/migration-from-v1
查重会限制用户的操作，暂不考虑添加（点击按钮应该会有反馈啊

**Comment by Linyoux** [comment]
> 1.中文介绍会在后续版本中更新（现在还没添加月幕作为数据源）
> 2.批量刮削具体是什么问题呢？
> 3.数据是可以继承的，具体操作可参考文档 https://vnite.ximu.dev/guide/migration-from-v1
> 4.查重会限制用户的操作，暂不考虑添加（点击按钮应该会有反馈啊

2.批量刮削无法刮削成功。（可能是我的问题？）
4.不限制用户的话可以弄个设置，在设置里面设定是否查重。
剥削完后确实可以连续点击识别，会有反馈弹窗，但还是能生成多个游戏副本。（就图上那样）

**Comment by ximu3** [comment]
我这边刚刚试了下批量刮削是可以工作的啊，请问是否可以给个日志（软件根目录logs文件夹下）或者更具体的描述呢？
查重设置我会在后续版本中尝试添加。
可以连续点击这个问题我会在后续版本修复。

**Comment by Linyoux** [comment]
> 我这边刚刚试了下批量刮削是可以工作的啊，请问是否可以给个日志（软件根目录logs文件夹下）或者更具体的描述呢？
> 查重设置我会在后续版本中尝试添加。
> 可以连续点击这个问题我会在后续版本修复。

批量剥削的bug我终于知道了，当我用steam数据源剥削完，失败后，切换其他数据源剥削，也会失败，如果一开始就用vndb那些就不会报错。  
@ximu3

**Comment by Linyoux** [comment]
> > 我这边刚刚试了下批量刮削是可以工作的啊，请问是否可以给个日志（软件根目录logs文件夹下）或者更具体的描述呢？
> > 查重设置我会在后续版本中尝试添加。
> > 可以连续点击这个问题我会在后续版本修复。
> 
> 批量剥削的bug我终于知道了，当我用steam数据源剥削完，失败后，切换其他数据源剥削，也会失败，如果一开始就用vndb那些就不会报错。
> 
> 原理估计是识别到了steam的游戏ID，然后这个ID在VNDB那些上不对应吧。  
> @ximu3 

复现失败了，没弄到log。但应该是识别了steamID，且steam剥削失败后，切换数据源时，这ID还留存着，导致其他数据源识别也失败。
批量剥削默认steam剥削器，但每次都要改，不如弄个默认剥削器设置，或者在批量剥削里选择全体剥削器，体验可能会好些。
@ximu3

**Comment by ximu3** [comment]
> > > 我这边刚刚试了下批量刮削是可以工作的啊，请问是否可以给个日志（软件根目录logs文件夹下）或者更具体的描述呢？
> > > 查重设置我会在后续版本中尝试添加。
> > > 可以连续点击这个问题我会在后续版本修复。
> > 
> > 
> > 批量剥削的bug我终于知道了，当我用steam数据源剥削完，失败后，切换其他数据源剥削，也会失败，如果一开始就用vndb那些就不会报错。
> > 原理估计是识别到了steam的游戏ID，然后这个ID在VNDB那些上不对应吧。
> > @ximu3
> 
> 复现失败了，没弄到log。但应该是识别了steamID，且steam剥削失败后，切换数据源时，这ID还留存着，导致其他数据源识别也失败。 批量剥削默认steam剥削器，但每次都要改，不如弄个默认剥削器设置，或者在批量剥削里选择全体剥削器，体验可能会好些。 @ximu3

设置中可以设置默认刮削器的

**Comment by Linyoux** [comment]
> > > > 我这边刚刚试了下批量刮削是可以工作的啊，请问是否可以给个日志（软件根目录logs文件夹下）或者更具体的描述呢？
> > > > 查重设置我会在后续版本中尝试添加。
> > > > 可以连续点击这个问题我会在后续版本修复。
> > > 
> > > 
> > > 批量剥削的bug我终于知道了，当我用steam数据源剥削完，失败后，切换其他数据源剥削，也会失败，如果一开始就用vndb那些就不会报错。
> > > 原理估计是识别到了steam的游戏ID，然后这个ID在VNDB那些上不对应吧。
> > > @ximu3
> > 
> > 复现失败了，没弄到log。但应该是识别了steamID，且steam剥削失败后，切换数据源时，这ID还留存着，导致其他数据源识别也失败。 批量剥削默认steam剥削器，但每次都要改，不如弄个默认剥削器设置，或者在批量剥削里选择全体剥削器，体验可能会好些。 @ximu3
> 
> 设置中可以设置默认刮削器的

好的好的
