### ISSUE TITLE
[Bug]: 需要低分辨率支持

### ISSUE THREAD

**Issue by hengxin001** [ximu3/vnite#95]
### 软件版本

2.0.0

### 问题描述

在目前的分辨率（1366*768）下，界面显示不全，并且无法将窗口调小。
主界面可以通过最大化解决问题，但子窗口既不能自由拖动，也不能调整大小，甚至在主窗口最大化的情况下，关闭按钮的显示位置和实际位置错位，必须退出主窗口最大化才能点击；如果子窗口大小过大，那么关闭按钮和确认按钮都无法点击，无法关闭子窗口。

### 问题日志

无特殊日志

### 问题截图

![_7ANK%~675VFZ7YHA(88X}H](https://github.com/user-attachments/assets/0db538a1-6916-46b4-abdb-856f1f4afb66)
![P3Q)CCB}K4CDQF1U USLV@A](https://github.com/user-attachments/assets/c56a87fa-a573-47f2-9d7f-f66598834ca3)

**Comment by ximu3** [comment]
了解了，我会尝试修复。

**Comment by ximu3** [comment]
新版本已初步修复该问题，还请更新。

**Comment by hengxin001** [comment]
> 新版本已初步修复该问题。

感谢，现在子窗口大小已经不影响正常使用了
